name: Build image

on:
  push:
    branches:
      - 'master'
    paths:
      - '1.22.0/**'
      - '.github/workflows/**'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      UNBOUND_VERSION: '1.22.0'
